# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb0dfbe085c09c91b6baf56a7ddbf9c9ceb40e7c279f9f1d9063e45b5991d4ff83afef6cf7a094767922be1c343b8b645f161ced6183929cf9fe62093824b7ea

test:
  secret_key_base: 0853b44cd3fc382be571897e68b8b81aa2024021ba7f7d65cbed30968a589c9f71fc15d69e909a2113e25b3708eeb41c91d7502a25a4df7b21b3493b6bd1c61a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
